import calculus_mikusi_nski_operational_calculi_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace calculus_mikusi_nski_operational_calculi_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end calculus_mikusi_nski_operational_calculi_theorem_canonical_lane_mathlib
end HautevilleHouse
